on:
  issue_comment:
    types: created
jobs:
  echo-timer:
    name: Cloud Echo Timer
    runs-on: ubuntu-latest
    steps:
      - name: Echo timer
        uses: thepwagner/echo-timer@master
        with:
          id: Cloud
          token: ${{ secrets.GITHUB_TOKEN }}
